import os
import itertools
import numpy as np
import pandas as pd
from tabulate import tabulate  # Run: pip install tabulate if missing

# ==========================================
# CONFIGURATION & SIMULATION PARAMETERS
# ==========================================
RESULTS_DIR = "results"
OPTIMIZER_OUTPUT_PATH = os.path.join(RESULTS_DIR, "strategy_optimization.csv")

# Search space dimensions (4 * 5 * 4 * 4 = 160 combinations)
HOLDING_DAYS_SPACE = [1, 2, 3, 5]
PROB_THRESHOLDS = [0.50, 0.55, 0.60, 0.65, 0.70]
TAKE_PROFITS = [None, 0.01, 0.02, 0.03]  # None, 1%, 2%, 3%
STOP_LOSSES = [None, 0.01, 0.02]        # None, 1%, 2%

INITIAL_CAPITAL = 100000.0  # Base calculation tracking
RISK_FREE_RATE = 0.07       # 7% Indian Risk-Free Rate baseline for Sharpe

def calculate_metrics(trades, initial_capital):
    """Calculates comprehensive quantitative metrics for a trade log."""
    if not trades:
        return {
            "Total Trades": 0, "Win Rate %": 0.0, "Total Return %": 0.0,
            "Avg Trade %": 0.0, "Profit Factor": 0.0, "Max Drawdown %": 0.0,
            "Sharpe Ratio": -99.0, "Final Capital": initial_capital
        }
    
    df_trades = pd.DataFrame(trades)
    returns = df_trades["return_pct"]
    
    # Win Rate
    wins = returns[returns > 0]
    losses = returns[returns <= 0]
    win_rate = (len(wins) / len(returns)) * 100
    
    # Returns
    total_return_pct = (df_trades["exit_cap"].iloc[-1] - initial_capital) / initial_capital * 100
    avg_trade_pct = returns.mean() * 100
    
    # Profit Factor
    gross_profits = wins.sum()
    gross_losses = abs(losses.sum())
    profit_factor = gross_profits / gross_losses if gross_losses > 0 else (gross_profits if gross_profits > 0 else 1.0)
    if gross_losses == 0 and gross_profits == 0:
        profit_factor = 1.0

    # Max Drawdown & Sharpe Calculation
    # Build equity curve sequentially from trade outcomes
    equity_curve = [initial_capital]
    for _, row in df_trades.iterrows():
        equity_curve.append(row["exit_cap"])
    equity_curve = np.array(equity_curve)
    
    # Max DD calculation
    peak = np.maximum.accumulate(equity_curve)
    drawdowns = (equity_curve - peak) / peak
    max_dd_pct = abs(drawdowns.min()) * 100
    
    # Sharpe Ratio (Using sequential trade-to-trade returns adjusted for baseline)
    trade_returns = np.diff(equity_curve) / equity_curve[:-1]
    excess_returns = trade_returns - (RISK_FREE_RATE / 252) # Scaled down per trade estimate
    if len(trade_returns) > 1 and excess_returns.std() > 0:
        sharpe = (excess_returns.mean() / excess_returns.std()) * np.sqrt(252)
    else:
        sharpe = 0.0
        
    return {
        "Total Trades": len(returns),
        "Win Rate %": round(win_rate, 2),
        "Total Return %": round(total_return_pct, 2),
        "Avg Trade %": round(avg_trade_pct, 2),
        "Profit Factor": round(profit_factor, 3),
        "Max Drawdown %": round(max_dd_pct, 2),
        "Sharpe Ratio": round(sharpe, 3),
        "Final Capital": round(equity_curve[-1], 2)
    }

def simulate_strategy(df, hold_days, threshold, tp, sl):
    """
    Simulates execution on chronological data tracking data window limits 
    to avoid lookahead contamination.
    """
    trades = []
    current_capital = INITIAL_CAPITAL
    in_position = False
    entry_idx = 0
    entry_price = 0.0
    
    # Expects columns: 'Close', 'High', 'Low', 'pred_prob' (probability generated by model)
    # Ensure dataframe is sorted chronologically
    df = df.sort_index()
    prices = df['Close'].values
    highs = df['High'].values if 'High' in df.columns else prices
    lows = df['Low'].values if 'Low' in df.columns else prices
    probs = df['pred_prob'].values
    
    i = 0
    while i < len(df):
        if not in_position:
            # Check entry condition
            if probs[i] >= threshold:
                in_position = True
                entry_idx = i
                entry_price = prices[i]
        else:
            # Inside a position: check exit criteria day-by-day
            days_held = i - entry_idx
            current_close = prices[i]
            current_high = highs[i]
            current_low = lows[i]
            
            # Check Stop Loss (if specified)
            if sl is not None:
                sl_price = entry_price * (1.0 - sl)
                if current_low <= sl_price:
                    # SL Triggered
                    ret = -sl
                    current_capital *= (1.0 + ret)
                    trades.append({"entry_i": entry_idx, "exit_i": i, "return_pct": ret, "exit_cap": current_capital})
                    in_position = False
                    i += 1
                    continue
            
            # Check Take Profit (if specified)
            if tp is not None:
                tp_price = entry_price * (1.0 + tp)
                if current_high >= tp_price:
                    # TP Triggered
                    ret = tp
                    current_capital *= (1.0 + ret)
                    trades.append({"entry_i": entry_idx, "exit_i": i, "return_pct": ret, "exit_cap": current_capital})
                    in_position = False
                    i += 1
                    continue
            
            # Check Time-based Holding Expiry
            if days_held >= hold_days or i == len(df) - 1:
                ret = (current_close - entry_price) / entry_price
                current_capital *= (1.0 + ret)
                trades.append({"entry_i": entry_idx, "exit_i": i, "return_pct": ret, "exit_cap": current_capital})
                in_position = False
        i += 1
        
    return calculate_metrics(trades, INITIAL_CAPITAL)

def main():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    
    # ----------------------------------------------------------------------
    # PLACEHOLDER GENERATION FOR STANDALONE TESTING
    # Replace this block with your actual loaded backtest/prediction dataframe
    # Expected file framework: pd.read_csv('results/TCS_test_predictions.csv', parse_dates=True, index_col=0)
    # ----------------------------------------------------------------------
    print("⏳ Loading backtest prediction datasets...")
    np.random.seed(42)
    date_rng = pd.date_range(start='2023-01-01', periods=250, freq='B')
    mock_df = pd.DataFrame(index=date_rng)
    mock_df['Close'] = 3000.0 + np.cumsum(np.random.normal(1, 15, size=(250,)))
    mock_df['High'] = mock_df['Close'] * 1.01
    mock_df['Low'] = mock_df['Close'] * 0.99
    # Simulate a model with subtle signals
    mock_df['pred_prob'] = np.random.uniform(0.4, 0.75, size=(250,))
    # ----------------------------------------------------------------------
    
    optimization_results = []
    
    # Generate search grid
    grid = list(itertools.product(HOLDING_DAYS_SPACE, PROB_THRESHOLDS, TAKE_PROFITS, STOP_LOSSES))
    print(f"🎯 Running Grid Optimization Search over {len(grid)} distinct strategies...")
    
    for hold, thresh, tp, sl in grid:
        metrics = simulate_strategy(mock_df, hold, thresh, tp, sl)
        
        strategy_summary = {
            "Holding Days": hold,
            "Prob Threshold": thresh,
            "Take Profit %": f"{tp*100}%" if tp else "None",
            "Stop Loss %": f"{sl*100}%" if sl else "None",
            **metrics
        }
        optimization_results.append(strategy_summary)
        
    df_results = pd.DataFrame(optimization_results)
    
    # Sorting optimization priorities: High Profit Factor -> High Sharpe -> Max Total Return
    df_results = df_results.sort_values(by=["Profit Factor", "Sharpe Ratio", "Total Return %"], ascending=[False, False, False])
    
    # Save complete run to CSV
    df_results.to_csv(OPTIMIZER_OUTPUT_PATH, index=False)
    print(f"💾 Complete optimization parameters saved to: {OPTIMIZER_OUTPUT_PATH}")
    
    # Format and present Top 20 layouts for immediate analysis
    top_20 = df_results.head(20)
    print("\n" + "="*80)
    print("🏆 TOP 20 EXECUTING TRADING STRATEGIES FOUND")
    print("="*80)
    print(tabulate(top_20.drop(columns=["Final Capital"]), headers="keys", tablefmt="grid", showindex=False))

if __name__ == "__main__":
    main()
